### ISSUE TITLE
Another order problem

### ISSUE THREAD

**Issue by jacksondc** [jacksondc/pottershell#10]
Is [orchideous](https://github.com/jacksondc/pottershell/blob/master/shell.aliases#L2) not backward?

**Comment by jacksondc** [comment]
And it looks like also reducto/shred and quill/nano (on line 1) is backward

**Comment by strugee** [comment]
Patched in 49a0e4e79a9c03287fc90998f876309d15a80a82, d144997936bc6abd3c1c148404c8c6b0588372cd, and 39885fd4302c0000b937cb95277bb877e783fc37.
