### ISSUE TITLE
Please move jacksondc/pottershell to pottershell/pottershell

### ISSUE THREAD

**Issue by strugee** [jacksondc/pottershell#11]
This will change the URL. I assume you're mostly OK with that.

I've changed my mind on how we should do releases. That's why this is happening. You'll be pleased - we're going to use [GitHub Releases](https://github.com/blog/1547-release-your-software).

**Comment by strugee** [comment]
And to be clear, by URL I mean the website URL, not the GitHub URL (although that will obviously also change, but GitHub provides redirects nowadays).

**Comment by jacksondc** [comment]
It seems a little unnecessary to have a whole organization for it, but if you want to switch it's fine with me. Also pottershell.github.io/pottershell is much uglier, but if you really want to switch that's fine (we could also get pottershell.com). Yay GitHub releases!

**Comment by strugee** [comment]
I was planning to switch the project page to an organization page, so we'd get pottershell.github.io.

That's a total of 3 repos already, and we _may_ want to add more in the future. I figured we'd have a separate org to not clutter upon your personal account. I've seen people do that for less repos.

**Comment by strugee** [comment]
I mean, if you don't mind having a couple Pottershell-related repos in your account, that's fine. I just figured it would be easier this way. Especially since then I don't have to bug you in case there's ever admin stuff, like repo creation or whatever.

**Comment by jacksondc** [comment]
No, it's fine. What do we need three repos for?

**Comment by strugee** [comment]
- pottershell.github.io
- data
- pottershell (basically the current repo, sans data + `gh-pages`)

I can also imagine splitting up the current repo into separate ones, for maintainability reasons (among others, e.g. we may want to have a separate repo if we ever, in the distant, distant future, support csh).

**Comment by jacksondc** [comment]
Doesn't splitting it up just make it more difficult to maintain?
